### ISSUE TITLE
static lib not build

### ISSUE THREAD

**Issue by navidad7** [pocoproject/openssl#1]
I wanted to build a static openssl library from this project. After buildall.cmd for static mode, I linked my program with produced static library (libcrypto.lib, libssl.lib) and I executed my program, "libssl.dll, libcrypto.dll is needed" alert windows appeared.

It seems that /MD{d} compile option is applied instead of /MT{d}

Please check build script..

my modified buildall.cmd is as follow..
------------
powershell -ExecutionPolicy RemoteSigned -File build.ps1 -openssl_release 1.1.0g -vs_version 140 -config both -platform Win32 -library static
powershell -ExecutionPolicy RemoteSigned -File build.ps1 -openssl_release 1.1.0g -vs_version 140 -config both -platform x64 -library static

**Comment by aleks-f** [comment]
@navidad7 [fixed](https://github.com/pocoproject/openssl/blob/develop/build.ps1#L402) (for now in develop branch only)
