### ISSUE TITLE
debug dll not found

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/openssl#3]
all DLLs (debug and release) are built with the same name (eg. `libcrypto.dll`); the problem is that, for the debug build, the DLL is later renamed (alongside `lib` and other artifacts). this results in debug applications (which link with the lib stub) being redirected to the original name (`libcrypto.dll`), which does not exist (because it was renamed to `libryptod.dll`)

@zosrothko fix coming soon, you'll want to update the binary distributions (if you are shipping debug binaries, otherwise this problem does not manifest)

**Comment by zosrothko** [comment]
@aleks-f Yeap, I will rebuild the distribution for poco-1.9.0
