### ISSUE TITLE
Build in Visual Studio 2019

### ISSUE THREAD

**Issue by Diversus23** [pocoproject/openssl#6]
Hi!
It's not work in VS 2019 :(
Help, please

**Comment by zosrothko** [comment]
@Diversus23 Which branch? What is the command line?

**Comment by Diversus23** [comment]
I updated the file **build.ps1**
- Added support for VS 2019
- Changed 7zip version
[build.zip](https://github.com/pocoproject/openssl/files/3931688/build.zip)

**Comment by zosrothko** [comment]
@Diversus23 Could you make a PR so your fix can be easily integrated? Thanks

**Comment by Diversus23** [comment]
> @Diversus23 Could you make a PR so your fix can be easily integrated? Thanks

@zosrothko Add PR
